name: CI

on:
  workflow_call:
  pull_request:
    branches:
      - main

jobs:
  format:
    # Set up operating system
    runs-on: ubuntu-latestd

    # Define job steps
    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Setup python
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        run: uv python install

      - uses: actions/setup-node@v6
        with:
          node-version: 25. # Same as in Dockerfile

      - name: Install dependencies
        run: npm install

      - name: Install pre-commit and run
        run: uvx pre-commit run --all-files
